### ISSUE TITLE
Missing Reference

### ISSUE THREAD

**Issue by hahsan-ti** [GSA/oscal-poam-to-word#1]
The code references `OSCALHelperClasses` and uses it in the `Default.aspx.cs` file. In the current state, the reference is not required for the application to build; however, it is not clear if it is required and should be used to perform a missing operation. Keeping the reference in the code is breaking the build, therefore, it must be removed. It is recommended to investigate if the reference is actually required for an operation currently not in the code.

**Comment by volpet2014** [comment]
The OSCALHelperClasses.dll is a hold over from the other converters and is not required for this version of the POAM converter.  Removing to complete the build and run will be acceptable as a solutions.
